import API_get_company from "./getCompany";
import API_add_company from "./addCompany";
import API_edit_company from "./editCompany";
import API_get_manager from "./getManager";
import API_get_employees from "./getEmployees";
import API_get_groups from "./getGroups";
import API_add_employees from "./addEmployees";
import API_get_history from "./getHistory";
import API_edit_count_places from "./editCountPlaces";
import API_edit_employees from "./editEmployees";
import API_get_photo from "./getPhoto";
import API_add_email from "./addEmail";
import API_get_emails from "./getEmails";
import API_save_photo from "./savePhoto";
import API_remove_email from "./removeEmail";
import API_delete_photo from "./deletePhoto";
import API_mailing_status_change from "./mailingStatusChange";

export const GetCompany = API_get_company;
export const AddCompany = API_add_company;
export const EditCompany = API_edit_company;
export const GetManager = API_get_manager;
export const GetEmployees = API_get_employees;
export const GetGroups = API_get_groups;
export const AddEmployess = API_add_employees;
export const GetHistory = API_get_history;
export const EditCountPlaces = API_edit_count_places;
export const EditEmployees = API_edit_employees;
export const GetPhoto = API_get_photo;
export const AddEmail = API_add_email;
export const GetEmails = API_get_emails;
export const SavePhoto = API_save_photo;
export const RemoveEmail = API_remove_email;
export const DeletePhoto = API_delete_photo;
export const MailingStatusChange = API_mailing_status_change;