export default {
    fees: null,
    cities: null,
    passenger: null,
    passenger_edit: null,
    provider: null,
    companies: null,
    provider_accounts: null,
    airlines: null,
    bc_type: null,
    controls_countries: null,
    controls_cities: null,
    controls_airports: null,
    service_class: null,
    current_fees: null,
}