import API_fees from "./fees";
import API_add_fees from "./addFees";
import API_edit_fees from "./editFees";
import API_get_cities from "./getCities";

export const Fees = API_fees;
export const AddFees = API_add_fees;
export const EditFees = API_edit_fees;
export const GetCities = API_get_cities;

import API_passenger from "./passengers";
import API_passenger_edit from "./editPassengers";
import API_passenger_search from "./searchPassengers";
import API_airlines from "./airlines";
import API_add_airlines from "./addAirlines";
import API_edit_airlines from "./editAirlines";
import API_CCA from "./countriesCitiesAiraports";
import API_provider from "./provider";
import API_provider_add from "./addProvider";
import API_provider_edit from "./editProvider";
import API_provider_account from "./providerAccount";
import API_provider_account_add from "./addProviderAccount";
import API_provider_account_edit from "./editProviderAccount";
import API_bc_type from "./bcType";
import API_bc_type_add from "./addBCType";
import API_bc_type_edit from "./editBCType";
import API_add_currency from "./addCurrency";
import API_edit_currency from "./editCurrency";
import API_fare_family from "./fareFamily";
import API_service_class_add from "./addServiceClass";
import API_service_class_edit from "./editServiceClass";
import API_country_city_airport from "./countryCityAirport";
import API_country_add from "./addCountry";
import API_country_edit from "./editCountry";
import API_city_add from "./addCity";
import API_city_edit from "./editCity";
import API_airport_add from "./addAirport";
import API_airport_edit from "./editAirport";
import API_time_limit_edit from "./editTimeLimit";
import API_get_fees from "./getFees";
import API_add_fees_controls from "./addFeesControls";
import API_edit_fees_controls from "./editFeesControls";

export const Passenger = API_passenger;
export const PassengerEdit = API_passenger_edit;
export const PassengerSearch = API_passenger_search;
export const Airlines = API_airlines;
export const AddAirlines = API_add_airlines;
export const EditAirlines = API_edit_airlines;
export const CCA = API_CCA;
export const Provider = API_provider;
export const AddProvider = API_provider_add;
export const EditProvider = API_provider_edit;
export const ProviderAccount = API_provider_account;
export const AddProviderAccount = API_provider_account_add;
export const EditProviderAccount = API_provider_account_edit;
export const BCType = API_bc_type;
export const AddBCType = API_bc_type_add;
export const EditBCType = API_bc_type_edit;
export const AddCurrency = API_add_currency;
export const EditCurrency = API_edit_currency;
export const FareFamily = API_fare_family;
export const AddServiceClass = API_service_class_add;
export const EditServiceClass = API_service_class_edit;
export const CountryCityAirport = API_country_city_airport;
export const AddCountry = API_country_add;
export const EditCountry = API_country_edit;
export const AddCity = API_city_add;
export const EditCity = API_city_edit;
export const AddAirport = API_airport_add;
export const EditAirport = API_airport_edit;
export const EditTimeLimit = API_time_limit_edit;
export const GetFees = API_get_fees;
export const AddFeesControls = API_add_fees_controls;
export const EsitFeesControls = API_edit_fees_controls;


