export const M_MENU_SHOW = "M_MENU_SHOW";
export const M_GET_COMPANY = "M_GET_COMPANY";
export const M_SET_CURRENT_COMPANY = "M_SET_CURRENT_COMPANY";
export const M_SET_CURRENT_EMPLOYEES = "M_SET_CURRENT_EMPLOYEES";