export const A_GET_GROUP = "A_GET_GROUP";
export const A_GET_PERMISSION = "A_GET_PERMISSION";
export const A_ADD_GROUP = "A_ADD_GROUP";
export const A_DELETE_GROUP = "A_DELETE_GROUP";
export const A_GETPERMISSION_BY_GROUP = "A_GETPERMISSION_BY_GROUP";
export const A_UPDATE_PERMISSION = "A_UPDATE_PERMISSION";
